### ISSUE TITLE
[Node.js Bootcamp] Project 0: Proxy Server - Ready for Review

### ISSUE THREAD

**Issue by gabhi** [gabhi/proxy-server-iojs#1]
My app is complete. /cc @codepathreview @codepath

Also, I have a question about this one part, was that the right approach? Also, how do I do this other thing?

**Comment by codepathreview** [comment]
Looks good! Hope you found this first project useful as a brief introduction or review of Node.js.

This was intended in part to give you a flavor for the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the bootcamp starts.

The next step is to continue working on extensions to your Node.js server. We will be confirming with you soon if you are going to be a part of the first Node.js bootcamp at Walmart Labs once we determine the location (Sunnyvale or San Bruno). Please email us at nodejs@codepath.com if you have any questions!

**Comment by gabhi** [comment]
Thanks @codepathreview . This is great. It has set great expectations.

Looking forward to meet you :+1:
